// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('../../../../src/bigwig/bigwig-exception.js', ['bigwig.BigwigException'], [], false);
goog.addDependency('../../../../src/bigwig/bigwig-file.js', ['bigwig.BigwigFile'], ['bigwig.BigwigReader', 'bigwig.ChrTree', 'bigwig.DataRecord', 'bigwig.IndexTree', 'bigwig.models.Header', 'goog.async.Deferred'], false);
goog.addDependency('../../../../src/bigwig/bigwig-reader.js', ['bigwig.BigwigReader'], ['bigwig.ChrTree', 'bigwig.models.BedGraphRecord', 'bigwig.models.BigwigStruct', 'bigwig.models.ChrTreeHeader', 'bigwig.models.ChrTreeNode', 'bigwig.models.ChrTreeNodeItem', 'bigwig.models.ChrTreeNodeLeaf', 'bigwig.models.FixedStepRecord', 'bigwig.models.Header', 'bigwig.models.RTreeHeader', 'bigwig.models.RTreeNode', 'bigwig.models.RTreeNodeItem', 'bigwig.models.RTreeNodeLeaf', 'bigwig.models.SectionHeader', 'bigwig.models.TotalSummary', 'bigwig.models.VariableStepRecord', 'bigwig.models.ZoomHeader', 'goog.async.Deferred', 'goog.math.Long', 'goog.string.format'], false);
goog.addDependency('../../../../src/bigwig/bigwig.js', ['bigwig'], ['bigwig.BigwigFile'], false);
goog.addDependency('../../../../src/bigwig/chr-tree.js', ['bigwig.ChrTree'], ['bigwig.Tree'], false);
goog.addDependency('../../../../src/bigwig/data-record.js', ['bigwig.DataRecord'], ['bigwig.IndexTree', 'bigwig.models.Record', 'bigwig.models.SectionHeader'], false);
goog.addDependency('../../../../src/bigwig/index-tree.js', ['bigwig.IndexTree'], ['bigwig.Tree', 'goog.math.Long'], false);
goog.addDependency('../../../../src/bigwig/models/bed-graph-record.js', ['bigwig.models.BedGraphRecord'], ['bigwig.models.BigwigStruct', 'bigwig.models.Record'], false);
goog.addDependency('../../../../src/bigwig/models/bigwig-struct.js', ['bigwig.models.BigwigStruct'], ['bigwig.BigwigException', 'goog.math.Long'], false);
goog.addDependency('../../../../src/bigwig/models/chr-tree-header.js', ['bigwig.models.ChrTreeHeader'], ['bigwig.models.BigwigStruct'], false);
goog.addDependency('../../../../src/bigwig/models/chr-tree-node-item.js', ['bigwig.models.ChrTreeNodeItem'], ['bigwig.models.BigwigStruct'], false);
goog.addDependency('../../../../src/bigwig/models/chr-tree-node-leaf.js', ['bigwig.models.ChrTreeNodeLeaf'], ['bigwig.models.BigwigStruct'], false);
goog.addDependency('../../../../src/bigwig/models/chr-tree-node.js', ['bigwig.models.ChrTreeNode'], ['bigwig.models.BigwigStruct'], false);
goog.addDependency('../../../../src/bigwig/models/fixed-step-record.js', ['bigwig.models.FixedStepRecord'], ['bigwig.models.BigwigStruct', 'bigwig.models.Record'], false);
goog.addDependency('../../../../src/bigwig/models/header.js', ['bigwig.models.Header'], ['bigwig.models.BigwigStruct'], false);
goog.addDependency('../../../../src/bigwig/models/r-tree-header.js', ['bigwig.models.RTreeHeader'], ['bigwig.models.BigwigStruct'], false);
goog.addDependency('../../../../src/bigwig/models/r-tree-node-item.js', ['bigwig.models.RTreeNodeItem'], ['bigwig.models.BigwigStruct'], false);
goog.addDependency('../../../../src/bigwig/models/r-tree-node-leaf.js', ['bigwig.models.RTreeNodeLeaf'], ['bigwig.models.BigwigStruct'], false);
goog.addDependency('../../../../src/bigwig/models/r-tree-node.js', ['bigwig.models.RTreeNode'], ['bigwig.models.BigwigStruct'], false);
goog.addDependency('../../../../src/bigwig/models/record.js', ['bigwig.models.Record'], [], false);
goog.addDependency('../../../../src/bigwig/models/section-header.js', ['bigwig.models.SectionHeader'], ['bigwig.models.BigwigStruct'], false);
goog.addDependency('../../../../src/bigwig/models/total-summary.js', ['bigwig.models.TotalSummary'], ['bigwig.models.BigwigStruct'], false);
goog.addDependency('../../../../src/bigwig/models/variable-step-record.js', ['bigwig.models.VariableStepRecord'], ['bigwig.models.BigwigStruct', 'bigwig.models.Record'], false);
goog.addDependency('../../../../src/bigwig/models/zoom-header.js', ['bigwig.models.ZoomHeader'], ['bigwig.models.BigwigStruct'], false);
goog.addDependency('../../../../src/bigwig/tree.js', ['bigwig.Tree'], [], false);
